### ISSUE TITLE
Divorce this project from schacon/grack

### ISSUE THREAD

**Issue by javanthropus** [grackorg/grack#7]
Pull requests by default go to schacon/grack, which makes submitting pull requests to this project more difficult than it should be.  We need to contact Github from the look of things and request that this project be configured to be an original project, not forked from schacon/grack, in order for the expected behavior to take effect.

**Comment by dometto** [comment]
Ah, good call, I hadn't realised this. I used a fork to make the historical ties explicit. Perhaps we can ping @schacon and ask him if there's anything that can be done from the github side. :)

**Comment by schacon** [comment]
I believe if you email support@github.com they can separate it for you.

**Comment by dometto** [comment]
Contacted support, let's see. :)

**Comment by javanthropus** [comment]
@dometto Any progress here?

**Comment by dometto** [comment]
Ah yes. They can proceed with the divorcing, but I need to change the mail address on my github account first so that it matches the address I'm using to contact them. Long story, but that's what it's stuck on. I'll try to get it done ASAP.

**Comment by dometto** [comment]
Done.
