### ISSUE TITLE
Release version 0.1.0

### ISSUE THREAD

**Issue by javanthropus** [grackorg/grack#8]
From what I can tell, there are no outstanding issues that should prevent the release of version 0.1.0.  The pre-releases have been out for several months.  Let's make this official.

**Comment by dometto** [comment]
Agreed!

**Comment by javanthropus** [comment]
I merged in a final test update.  That's the only change on top of the v0.1.0.pre2 tag at the moment.

**Comment by dometto** [comment]
I will remove the compatibility adapter and then cut the new release.

**Comment by dometto** [comment]
Done!
